### ISSUE TITLE
Token not set during registration 

### ISSUE THREAD

**Issue by sanjaysagar12** [dharshan-kumarj/RestAPI-Automation-Frontend#1]
token undefined 

![Screenshot from 2024-05-30 11-03-47](https://github.com/dharshan-kumarj/RestAPI-Automation-Frontend/assets/153230367/6c622068-add6-446a-99cd-f4955794930a)

**Comment by dharshan-kumarj** [comment]
defined token and update the code for the above issue in the follwing commit
b99fbd2
